api/urls.py
from django.urls import re_path, path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    HomePageAPIView, PostDetailAPIView,
    FilterListView, FilterTopListView,
    CategoryListView, TagListView,
    FirstCategoryListView, LastCategoryListView,    
    site_uml
    )

urlpatterns = [
    re_path(r'^home/$', HomePageAPIView.as_view(), name="home"),
    re_path(r'^category/$', CategoryListView.as_view(), name='category'),
    re_path(r'^first_category/$', FirstCategoryListView.as_view(), name='first_category'),
    re_path(r'^last_category/$', LastCategoryListView.as_view(), name='last_category'),
    re_path(r'^tag/$', TagListView.as_view(), name='category'),
    re_path(r'^filter/$', FilterListView.as_view(), name='filter'),
    re_path(r'^post/$', PostDetailAPIView.as_view(), name="post"),
    re_path(r'^filter_top/$', FilterTopListView.as_view(), name='filter_top'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('site_uml/', site_uml, name='site_uml'),


]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path("post/<slug>", views.PostDetailView.as_view(), name='post_detail'),
    
    path('filter/<str:by_what>', views.MainPostsView.as_view(), name='filter_by_something'),
    
    path("category/<slug>", views.CategoryListView.as_view(), name='category_list'),
    path("tag/<slug>", views.TagListView.as_view(), name='tag_list'),
    
    
    path('react/', views.post_reaction_view, name='post_react'),
    # Follows
    
    
    path('search/', views.inline_search, name='search'), 
    path('contact/', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from api.urls import urlpatterns as api_url
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('api/v1/', include(api_url)),    
    path('api/v1/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('master/', admin.site.urls),    
    path('', include("blog.urls", namespace='blog')),  
]

handler404 = 'blog.views.myhandler404'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();
   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(95266336, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/95266336" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<noscript><div><img src="https://mc.yandex.ru/watch/92161304" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
    <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WCZCWM5');</script>
    
   <!-- End Google Tag Manager -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="yandex-verification" content="6f5f50298c460b67" />
    <meta name="google-site-verification" content="YvmMznWrKMTkzmtTOYx8mb8k-2EmNaywBAimqFDg4Ds" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Abdurakhmon Rashidov">
    
    <meta name="description" content="pyblog bu Python va dasturlashga oid o’zbek tilidagi blog. Hozirda Python, Javascript, Dasturlash, Veb dasturlash ,Foundation va boshqa turkumlarga va o’nlab teglarga mansub maqolalar saytdan joy olgan.">
    <meta name="keywords" content="Dasturlash , Blog, Python , Payton, dasturchi, Javascript, maqola, yangilik, dastur,">
    {% if post %}
    
    
    
    
    <meta property="og:site_name" content="pyblog.uz - Abdurahmon Rashidov"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{post.title}}"/>
    <meta property="og:description" content="{{post.plain}}"/>
    <meta property="og:image" content="{{post.image_url}}"/>
    <meta property="og:url" content="https://pyblog.uz/post/{{post.slug}}"/>
    {% else %}
    <meta property="og:title" content="Python va dasturlash haqida o'zbek tilidagi blog.">
    <meta property="og:site_name" content="pyblog.uz">
    <meta property="og:url" content="https://pyblog.uz">
    <meta property="og:description" content="pyblog.uz bu python va dasturlashga oid o'zbek tilidagi sifatli maqola , tutoriallar berib boruvchi blog hisoblanadi.">
    <meta property="og:type" content="website">
    <meta property="og:image" content="{% static 'assets/images/HEAD.svg' %}">
    {% endif %}

    <!-- Links -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="shortcut icon" href="{% static 'assets/images/HEAD.svg' %}" type="image/x-icon">
{% block title %}
    <title>pyblog.uz - Abdurahmon Rashidov</title>
{% endblock %}

    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-B72B625YDN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-B72B625YDN');
</script>



</head>

<body>
    <header>
        <div class="container">
            <div class="section-wrapp">
                <div class="header-wrapper">
                    <a href="/">
                        <img class="header-logo_img" src="{% static 'assets/images/HEAD.svg' %}" alt="">
                        <span class="btn-shine">BETA</span>
                    </a>

                    <div class="header-details_wrapper">
                        <form action="" class="header-search_form">
                            <div class="header-search_wrapper">
                                <div class="header-search_inner">
                                    <input type="text" id="s_query" onkeyup="fetchQueryData(this.value)" class="s_query" name="s_query"
                                        placeholder="shu yerga yozasiz..." autocomplete="off">
                                    <button type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>

                                    <!-- Search resultlar -->
                                    <div class="header-res_wrapper cleared noned">
                                        <p class="header-res_heading">
                                            Yangi postlar
                                        </p>

                                        <p class="header-close">
                                            <i class="fas fa-close"></i>
                                        </p>
                                        {% if not page_obj %}
                                        {% for post in related_posts|slice:'3' %}
                                        <div class="header-res_item" id="default_posts">
                                            <a href="{% url 'blog:post_detail' post.slug %}" class="header-res_item_link">
                                                <img class="header-res_item_img" src="{{post.image_url}}"
                                                    alt="{{post.title}}">
                                                    {{post.title}}
                                            </a>
                                        </div>
                                        {% endfor %}
                                        {% else %}
                                        {% for post in page_obj|slice:'3' %}
                                        <div class="header-res_item" id="default_posts">
                                            <a href="{% url 'blog:post_detail' post.slug %}" class="header-res_item_link">
                                                <img class="header-res_item_img" src="{{post.image_url}}"
                                                    alt="{{post.title}}">
                                                    {{post.title}}
                                            </a>
                                        </div>
                                        {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="header-search_bg"></div>
                            </div>
                            <div class="header-search_opener">
                                <i class="fas fa-search"></i>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </header>
{% block content %}
{% endblock %}
<footer>
    <div class="section-wrapp">
        <div class="container">
            <ul class="footer-list">
                <li class="footer-item">
                    <a href="/">
                        <img src="{% static 'assets/images/HEAD.svg' %}" alt="Logo">
                        <span class="btn-shine">BETA</span>
                    </a>
                    <p class="footer-text_info">
                        Python hamda dasturlashga oid o’zbek <br>
                        tilidagi blog. 
                    </p>
                 
                </li>

                <li class="footer-item">
                    <ul class="footer-links_list">
                        <li class="footer-link_item link"><a href="/">Bosh sahifa</a></li>
                        <li class="footer-link_item link"><a href="{% url 'blog:contact' %}">Bog’lanish</a></li>
                        <li class="footer-link_item link">
                            <button href="#" class="header-user_switcher">
                                <i class="fas fa-moon"></i>
                            </button>
                        </li>
                    </ul>
                </li>

                <li class="footer-item">
                    <ul class="footer-links_list">
                        <li class="footer-link_item telegram social_link">
                            <a href="https://t.me/pybloguz">
                                <i class="fab fa-telegram"></i>
                                Telegram
                            </a>
                        </li>
                        <li class="footer-link_item instagram social_link">
                            <a href="https://www.instagram.com/pyblog.uz/">
                                <i class="fab fa-instagram"></i>
                                Instagram
                            </a>
                        </li>
                        <li class="footer-link_item facebook social_link">
                            <a href="https://www.facebook.com/pybloguz">
                                <i class="fab fa-facebook"></i>
                                Facebook
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

            <p class="footer-information_text">

                pyblog.uz by <a href="https://www.instagram.com/rashidov_21/">Abdurakhmon Rashidov</a> created with <i class="fas fa-heart"></i> akalar.
            </p>
        </div>
    </div>
</footer>
<script src="{% static 'assets/js/search.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
{% if request.path == "/" or "filter" in request.path %}
<script src="{% static 'assets/js/home.js' %}"></script>
{% endif %}
<script src="{% static 'assets/lib/js/smooth-scroll.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Bog'lanish - pyblog.uz</title>
{% endblock %}


{% block content %}


    <main>
        <div class="contact">
            <div class="section-wrapp">
                <div class="container">
                    <div class="contact-info_wrapper">
                        <div class="contact-info shadowed">
                            <h1 class="contact-heading">Aloqa</h1>
                            <br>
                            <h3 class="contact-subheading">Savol va takliflar masalasida bog’lanish uchun
                                ma’lumotlarimiz</h3>

                            <p class="contact-text_info">Elektron manzilimiz: <a
                                    href="mailto:support@pyblog.uz">support@pyblog.uz</a>
                            </p>

                            <p class="contact-text_info">Manzilimiz: <a href="#">170100 , Andijon
                                    shahar, Sog’lom Avlod ko’chasi 24a
                                    - uy</a>
                            </p>

                            <p class="contact-text_info">Blogni ijtimoiy tarmoqlarda ulashish:</a>
                            </p>

                            <div class="contact-socials_list">
                                <a href="#" class="contact-social_item facebook">
                                    <i class="fab fa-facebook"></i>
                                </a>

                                <a href="#" class="contact-social_item instagram">
                                    <i class="fab fa-instagram"></i>
                                </a>

                                <a href="#" class="contact-social_item telegram">
                                    <i class="fab fa-telegram"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
<br>
<br>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% load static %} 

{% block title %}
    <title>{{post.title}}</title>
{% endblock %}

{% block content %}




<link  rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai-sublime.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
<script>
  hljs.highlightAll();

  document.addEventListener("DOMContentLoaded", (event) => {
    document.querySelectorAll("pre").forEach((el) => {
      el.classList.add("language-python")
        hljs.highlightElement(el);
    });
  });
  


</script>

<style>
  main * {
    list-style: auto !important;
  }
  ul,
  ol {
    margin-left: 40px;
  }
  .ql-syntax {
    padding: 10px;
    border-radius: 5px;
    font-family: Arial, Helvetica, sans-serif;
    overflow-x:scroll;
  }
  .post_detail-content p img{
    max-width: 100%;
  }
</style>
<main>
  <div class="message active">
    <p class="message_info">Saqlab olindi !</p>
    <i class="fas fa-xmark" onclick="clearMessage(this)"></i>
  </div>
  <div class="post_detail">
    <div class="section-wrapp">
      <div class="container">
        <div class="post_wrapper shadowed">
          <div class="post_heading">
            <a href="#">
              <i class="{{post.icon}}"></i>
            </a>
            <h1>{{post.title}}</h1>
          </div>

          <div class="post_info-wrapper">
            <a href="#">
              <i class="fas fa-user" style="color: #6ea7e0;"></i>
              {{post.author.get_full_name}}
            </a>

            <a href="{% url 'blog:category_list' post.category.slug %}">
              <i class="{{post.category.icon}}"></i>
              {{post.category}}
            </a>

            <span>
              <i class="fas fa-eye" style="color: #6ea7e0;"></i>
              {{post.views}}
            </span>

            <span>
              <i class="fas fa-fire-flame-curved" style="color: orange;"></i>
              {{post.get_all_reaction_count}}
            </span>
          </div>

          <div class="post_detail-content">
            <p>{% autoescape off %} {{post.body.html}} {% endautoescape %}</p>
          </div>

          <div class="post_detail-bottom_info">
            <div class="post_detail-bottom_reaction">
              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">+{{post.good}}</p>
                <img
                  onclick="postReact({{post.id}}, 'good')"
                  src="{% static './assets/emojies/thumbs_up.png' %}"
                  width="32"
                  height="32"
                  alt="👍"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">+{{post.like}}</p>
                <img
                  onclick="postReact({{post.id}}, 'like')"
                  src="{% static './assets/emojies/heart.png' %}"
                  width="32"
                  height="32"
                  alt="❤"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">+{{post.great}}</p>
                <img
                  onclick="postReact({{post.id}}, 'great')"
                  src="{% static './assets/emojies/sunglass_face.png' %}"
                  width="32"
                  height="32"
                  alt="😎"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">+{{post.fire}}</p>
                <img
                  onclick="postReact({{post.id}}, 'fire')"
                  src="{% static './assets/emojies/fire.png' %}"
                  width="32"
                  height="32"
                  alt="💥"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">
                  +{{post.legend}}
                </p>
                <img
                  onclick="postReact({{post.id}}, 'legend')"
                  src="{% static './assets/emojies/alien.png' %}"
                  width="32"
                  height="32"
                  alt="👽"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">
                  +{{post.neutral}}
                </p>
                <img
                  onclick="postReact({{post.id}}, 'neutral')"
                  src="{% static './assets/emojies/neutral_face.png' %}"
                  width="32"
                  height="32"
                  alt="😐"
                />
              </span>

              <span class="post_detail-bottom_reaction_item">
                <p class="post_detail-bottom_reaction_title">
                  +{{post.dislike}}
                </p>
                <img
                  onclick="postReact({{post.id}}, 'dislike')"
                  src="{% static './assets/emojies/thumbs_down.png' %}"
                  width="32"
                  height="32"
                  alt="👎"
                />
              </span>
            </div>

            <div class="post_detail-bottom_tags">
              <h3 class="post_detail-bottom_title">Maqola teglari</h3>

              <div class="post_detail-tag_wrapper">
                {% for tag in post.tags.all %}
                <a
                  href="{% url 'blog:tag_list' tag.slug %}"
                  class="post_detail-tag_item"
                >
                  <i class="{{tag.icon}}"></i>
                  {{tag.title}}
                </a>
                {% endfor %}
              </div>
            </div>
          </div>

          <div class="post_detail-down">
            <div class="post_detail-down_author">
              <a href="#">
                <i class="fas fa-user" style="color: #6ea7e0;"></i>
                {{post.author.get_full_name}}
              </a>

              <a href="{% url 'blog:category_list' post.category.slug %}">
                <i class="{{post.category.icon}}"></i>
                {{post.category}}
              </a>

              <span>
                <i class="fas fa-eye" style="color: #6ea7e0;"></i>
                {{post.views}}
              </span>
            </div>

            <div class="post_detail-down_socials">
              <a href="https://www.facebook.com/sharer/sharer.php?u=https://pyblog.uz/post/{{post.slug}}" target="_blank">
                <i class="fab fa-facebook"></i>
                Facebook
              </a>

              <a href="https://t.me/share/url?url=https://pyblog.uz/post/{{post.slug}}&text={{post.title}}" target="_blank">
                <i class="fab fa-telegram"></i>
                Telegram
              </a>
            </div>
          </div>
        </div>
        <br />
        <div class="post_related_blocks">
          <div class="post_related shadowed">
            <h1 class="post_additional-heading">Bu haftada ko'p o'qildi</h1>
            {% for post in most_read %}
            <div class="post_related-item">
              <a href="{% url 'blog:post_detail' post.slug %}" style="display:flex; gap:10px;">
                  <img src="{{post.image_url}}" alt="{{post.title}}" />
                <div>
                  <h1>
                    {{post.title}}
                   
                  </h1> 
                  <span>
                    <i class="fas fa-eye" style="color: #6ea7e0;"></i>
                    {{post.views}}
                  </span>  
                  <span>
                    <i class="fas fa-fire-flame-curved" style="color: orange;"></i>
                    {{post.get_all_reaction_count}}
                  </span>
                </div>            
              </a>
            </div>
            {% empty %}
            <h1>Hozircha maqolalar mavjud emas !</h1>
            {% endfor %}
          </div>
          <div class="post_related shadowed">
            <h1 class="post_additional-heading">Mavzuga oid</h1>
            {% for post in related_posts %}
            <div class="post_related-item">
              <a href="{% url 'blog:post_detail' post.slug %}">
                  <img src="{{post.image_url}}" alt="{{post.title}}" />
                  <div>
                    <h1>
                      {{post.title}}                     
                    </h1> 
                    <span>
                      <i class="fas fa-eye" style="color: #6ea7e0;"></i>
                      {{post.views}}
                    </span>  
                    <span>
                      <i class="fas fa-fire-flame-curved" style="color: orange;"></i>
                      {{post.get_all_reaction_count}}
                    </span>
                  </div>              
              </a>
            </div>
            {% empty %}
            <h1>Hozircha maqolalar mavjud emas !</h1>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}